# syntax=docker/dockerfile:1

FROM confluentinc/cp-kafka-connect-base:6.2.0

WORKDIR /home
COPY Scripts/connect_script ./

RUN confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:10.2.5

WORKDIR /usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc/lib