# syntax=docker/dockerfile:1

# FROM mysql:8.0
# FROM mysql/mysql-server:8.0
FROM linuxserver/mariadb:alpine

RUN rm -rf /docker-entrypoint-initdb.d/init.sql
ADD ./Scripts/init.sql /docker-entrypoint-initdb.d/init.sql
RUN chmod -R 775 /docker-entrypoint-initdb.d

ENV MARIADB_ROOT_PASSWORD capstone