#!/bin/bash
echo 'Setting up Topic. . .'
python ./topic_setup.py --topic sensor_data
# echo 'Sending records. . .'
# python ./send_record.py --topic sensor_data --record-value '10,11,33,False'
echo 'Receiving records. . .'
python -u ./receive_record.py --topic sensor_data
echo '---------------Done---------------'