#!/bin/bash
# Launch Kafka Connect
/etc/confluent/docker/run &
#
# Wait for Kafka Connect listener
echo "Waiting for Kafka Connect to start listening on localhost ⏳"
while : ; do
  curl_status=$$(curl -s -o /dev/null -w %{http_code} http://localhost:8083/connectors)
  echo -e $$(date) " Kafka Connect listener HTTP state: " $$curl_status " (waiting for 200)"
  if [ $$curl_status -eq 200 ] ; then
    break
  fi
  sleep 5
done

curl -X POST \
  -H "Content-Type: application/json" \
    --data '{ 
        "name": "quickstart-jdbc-sink", 
        "config": { 
            "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector", 
            "tasks.max": 1, 
            "connection.url": "jdbc:mysql://127.0.0.1:3306/root_access?user=cmst&password=agroponics", 
            "mode": "incrementing", 
            "incrementing.column.name": "id", 
            "timestamp.column.name": "datetime", 
            "topic.prefix": "_connect_", 
            "poll.interval.ms": 1000 } }'

# This needs swapped with a mySQL Sink
# echo -e "\n--\n+> Creating Data Generator source"
# curl -s -X PUT -H  "Content-Type:application/json" http://localhost:8083/connectors/source-datagen-01/config \
#     -d '{
#     "connector.class": "io.confluent.kafka.connect.datagen.DatagenConnector",
#     "key.converter": "org.apache.kafka.connect.storage.StringConverter",
#     "kafka.topic": "sensor_data",
#     "max.interval":750,
#     "quickstart": "ratings",
#     "tasks.max": 1
# }'
# sleep infinity